//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mazina_GlazkiSave
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Mazina_GLAZKIEntities1 : DbContext
    {
        private static Mazina_GLAZKIEntities1 _context;

        public static Mazina_GLAZKIEntities1 GetContext()
        {
            if (_context == null)
                _context = new Mazina_GLAZKIEntities1();
            return _context;
        }
        public Mazina_GLAZKIEntities1()
            : base("name=Mazina_GLAZKIEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Agent> Agent { get; set; }
        public DbSet<AgentPriorityHistory> AgentPriorityHistory { get; set; }
        public DbSet<AgentType> AgentType { get; set; }
        public DbSet<Material> Material { get; set; }
        public DbSet<MaterialCountHistory> MaterialCountHistory { get; set; }
        public DbSet<MaterialType> MaterialType { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ProductCostHistory> ProductCostHistory { get; set; }
        public DbSet<ProductMaterial> ProductMaterial { get; set; }
        public DbSet<ProductSale> ProductSale { get; set; }
        public DbSet<ProductType> ProductType { get; set; }
        public DbSet<Shop> Shop { get; set; }
        public DbSet<Supplier> Supplier { get; set; }
        
        public int Discount { get; set; }
    }
}
